name = "accumedia"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "76deaf70d0a6448c82cac8598146eb26"

[vars]
NEXT_PUBLIC_APP_URL = "https://accumedia.inofinix.com"
AUTH_REQUIRED = "true"
ALLOW_EXTERNAL_ASR = "true"

[[services]]
binding = "VIDEO_RENDER_SERVICE"
service = "accumedia-video-renderer"

[[services]]
binding = "EMAIL_SERVICE"
service = "accumedia-video-renderer"
